# Generated by Django 4.2.1 on 2023-09-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_doctor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('Date_of_birth', models.CharField(max_length=255)),
                ('Age', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=255)),
                ('Address', models.TextField()),
                ('visit_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
