# Generated by Django 4.2.1 on 2023-09-28 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='visit_date',
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='registration_number')),
                ('Time_Slot', models.CharField(choices=[('10AM-11AM', '10AM-11AM'), ('11AM-12pm', '11AM-12pm'), ('12PM-01PM', '12PM-01PM'), ('2PM-3PM', '2PM-3PM'), ('3PM-4PM', '3PM-4PM'), ('4PM-5PM', '4PM-5PM'), ('6PM-7PM', '6PM-7PM'), ('7PM-8PM', '7PM-8PM'), ('8PM-9PM', '8PM-9PM')], max_length=200)),
                ('Token_Number', models.CharField(max_length=255)),
                ('Problem', models.TextField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.specialization')),
                ('Doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
