# Generated by Django 4.2.1 on 2023-09-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_remove_patient_visit_date_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visit_date',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
