# Generated by Django 4.2.1 on 2023-09-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_doctor_consultation_fee_alter_appointment_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Rescheduled', 'Rescheduled')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.IntegerField(default=1500),
        ),
    ]
