# Generated by Django 4.2.1 on 2023-09-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_appointment_status_alter_doctor_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visit',
            field=models.BooleanField(default=False),
        ),
    ]
