# Generated by Django 4.2.1 on 2023-09-29 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_roomnumber_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allotment_date', models.CharField(max_length=255)),
                ('discharged_date', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.roomnumber')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.room_info')),
            ],
        ),
    ]
