# Generated by Django 4.2.1 on 2023-09-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemailtomyemail', '0002_rename_name_contactus_fname_remove_contactus_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
